### ISSUE TITLE
i cant load the plugin

### ISSUE THREAD

**Issue by TLOvO** [TheLimeGlass/Khoryl#20]
Khoryl version 1.0.5
minecraft version 1.12.2
server version paperspigot 1.12.2
skript version 2.6.2

```
Could not load 'plugins\Khoryl-1.0.5.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/limeglass/khoryl/Khoryl has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:318) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[Paper-1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
Caused by: java.lang.UnsupportedClassVersionError: me/limeglass/khoryl/Khoryl has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_291]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_291]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_291]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[Paper-1.12.2.jar:git-Paper-1618]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_291]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_291]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[Paper-1.12.2.jar:git-Paper-1618]
        ... 6 more
```

**Comment by ImNotStable** [comment]
What java version are you running
me/limeglass/khoryl/Khoryl has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by ImNotStable** [comment]
@TLOvO

**Comment by TheLimeGlass** [comment]
Requires Java 17

**Comment by TLOvO** [comment]
> 

ok thank its work!!!!!

**Comment by TLOvO** [comment]
> Requires Java 17, you can run 1.12 with Java 17.

`[02:57:22 INFO]: [MythicMobsExtension] Enabling MythicMobsExtension v1.738c-SNAPSHOT
[02:57:22 WARN]: [MythicMobsExtension] EntityTransformEvent not found, can't prevent mobs naturally transforming
[02:57:22 WARN]: [MythicMobsExtension] TimeSkipEvent not found, can't synchronize time between worlds
[02:57:22 WARN]: [MythicMobsExtension] Use an updated version of Spigot for better knowledge book recipes
[02:57:22 WARN]: [MythicMobsExtension] Could not bind to chunk ticket API, chunk locking will not work
[02:57:22 WARN]: [MythicMobsExtension] No phantoms on this version
[02:57:22 WARN]: [MythicMobsExtension] Could not bind to persist entity tag, can't make mobs persistent
[02:57:22 WARN]: [MythicMobsExtension] Could not bind to selectEntities method, command target selectors may not work
[02:57:22 WARN]: [MythicMobsExtension] Couldn't find recipe removal method, this is odd since we did find NamespacedKey
[02:57:22 WARN]: [MythicMobsExtension] Couldn't find recipe discover method, this is odd since we did find NamespacedKey
[02:57:22 WARN]: [MythicMobsExtension] Could not bind to auto block state methods
[02:57:22 INFO]: [MythicMobsExtension] enabled externals
[02:57:22 INFO]: [MythicMobsExtension] registered mechanics!
[02:57:22 INFO]: [MythicMobsExtension] registered conditions!
[02:57:22 INFO]: [MythicMobsExtension] registered targeters!
[02:57:22 INFO]: [MythicMobsExtension] enabled javascript!
[02:57:22 INFO]: [MythicMobsExtension] using MythicPlayers
[02:57:22 INFO]: [MythicMobsExtension] using HolograpicDisplays
[02:57:22 INFO]: [MythicMobsExtension] using ProtocolLib
[02:57:22 INFO]: [MythicMobsExtension] registered mme placeholders
[02:57:22 INFO]: [Khoryl] Enabling Khoryl v1.0.5
[02:57:22 ERROR]: Error occurred while enabling Khoryl v1.0.5 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/block/data/AnaloguePowerable
        at me.limeglass.khoryl.elements.block.analoguepowerable.ExprMaxPower.<clinit>(ExprMaxPower.java:18) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:117) ~[?:?]
        at me.limeglass.khoryl.Khoryl.onEnable(Khoryl.java:34) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[Paper-1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.block.data.AnaloguePowerable
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:109) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[Paper-1.12.2.jar:git-Paper-1618]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 16 more
[02:57:22 INFO]: [Khoryl] Disabling Khoryl v1.0.5`
i update java to 17
but it no work

**Comment by TheLimeGlass** [comment]
That's a different error, can you please report as a new issue?
