### ISSUE TITLE
Issue with SkBee

### ISSUE THREAD

**Issue by ImNotStable** [TheLimeGlass/Khoryl#22]
[06:18:13 ERROR]: #!#!
[06:18:13 ERROR]: #!#! [Skript] Severe Error:
[06:18:13 ERROR]: #!#! Could not load economy\tokens.sk
[06:18:13 ERROR]: #!#!
[06:18:13 ERROR]: #!#! Something went horribly wrong with Skript.
[06:18:13 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[06:18:13 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[06:18:13 ERROR]: #!#! Here is full list of them:
[06:18:13 ERROR]: #!#! skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders) Diskuise v0.2-beta3 TuSKe v2.1 (github.com/Tuke-Nuke/TuSKe) SkJade v1.4.1 (https://www.github.com/Ankoki-Dev/SkJade) Khoryl v1.0.5 SkBee v1.17.0-Beta1 (https://github.com/ShaneBeee/SkBee) Skacket v1.0.10 SkQuery v4.1.6
[06:18:13 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[06:18:13 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[06:18:13 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[06:18:13 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[06:18:13 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[06:18:13 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[06:18:13 ERROR]: #!#!
[06:18:13 ERROR]: #!#! Stack trace:
[06:18:13 ERROR]: #!#! java.lang.RuntimeException: pattern compiling exception, element class: me.limeglass.khoryl.elements.entity.llama.ExprLlamaDecor
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:343)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:615)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.VariableString.newInstance(VariableString.java:255)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.VariableString.newInstance(VariableString.java:131)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:514)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:741)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:121)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:57)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1243)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:753)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.Skript$1.run(Skript.java:786)
[06:18:13 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[06:18:13 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[06:18:13 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[06:18:13 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[06:18:13 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[06:18:13 ERROR]: #!#! Caused by: ch.njol.skript.patterns.MalformedPatternException: caught exception while compiling pattern [pattern: [the] [llama] [inventory] decor [item] of %llamainventories%]
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:54)
[06:18:13 ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1242)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:343)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:615)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.VariableString.newInstance(VariableString.java:255)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.VariableString.newInstance(VariableString.java:131)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:514)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:741)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:121)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:57)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1243)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:753)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.Skript$1.run(Skript.java:786)
[06:18:13 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[06:18:13 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[06:18:13 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[06:18:13 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[06:18:13 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[06:18:13 ERROR]: #!#! Caused by: ch.njol.skript.SkriptAPIException: No class info found for llamainventory
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:92)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:138)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:49)
[06:18:13 ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1242)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:343)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:615)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.VariableString.newInstance(VariableString.java:255)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.VariableString.newInstance(VariableString.java:131)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:514)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:741)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:121)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:57)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1243)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:753)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[06:18:13 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.Skript$1.run(Skript.java:786)
[06:18:13 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[06:18:13 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[06:18:13 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[06:18:13 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[06:18:13 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[06:18:13 ERROR]: #!#!
[06:18:13 ERROR]: #!#! Version Information:
[06:18:13 ERROR]: #!#!   Skript: 2.6.2
[06:18:13 ERROR]: #!#!     Flavor: skriptlang-github
[06:18:13 ERROR]: #!#!     Date: 19:12:53.596652600
[06:18:13 ERROR]: #!#!   Bukkit: 1.18.2-R0.1-SNAPSHOT
[06:18:13 ERROR]: #!#!   Minecraft: 1.18.2
[06:18:13 ERROR]: #!#!   Java: 17.0.3.1 (Java HotSpot(TM) 64-Bit Server VM 17.0.3.1+2-LTS-6)
[06:18:13 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[06:18:13 ERROR]: #!#!
[06:18:13 ERROR]: #!#! Server platform: Paper
[06:18:13 ERROR]: #!#!
[06:18:13 ERROR]: #!#! Current node: set result to "%0 + {tokens::%event-player's uuid%}%" (economy\tokens.sk, line 5)
[06:18:13 ERROR]: #!#! Current item: null
[06:18:13 ERROR]: #!#!
[06:18:13 ERROR]: #!#! Thread: Server thread
[06:18:13 ERROR]: #!#!
[06:18:13 ERROR]: #!#! Language: english
[06:18:13 ERROR]: #!#! Link parse mode: DISABLED
[06:18:13 ERROR]: #!#!
[06:18:13 ERROR]: #!#! End of Error.
[06:18:13 ERROR]: #!#!

Issue is fixed once SkBee is removed

**Comment by TheLimeGlass** [comment]
Fixed in 1.0.6
