### ISSUE TITLE
huge error when using swim effect

### ISSUE THREAD

**Issue by aabssmc** [TheLimeGlass/Khoryl#44]
idk how to make errors on specific classes but i was told to make one on the `SetEffect.java` class, here is the error:

```
[03:00:23 ERROR]: #!#! >
[03:00:23 ERROR]: #!#! [Skript] Severe Error:>
[03:00:23 ERROR]: #!#! Unexpected error while executing effect command 'make target entity swimming' by 'aabss'>
[03:00:23 ERROR]: #!#! >
[03:00:23 ERROR]: #!#! Something went horribly wrong with Skript.>
[03:00:23 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.>
[03:00:23 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).>
[03:00:23 ERROR]: #!#! Here is full list of them:>
[03:00:23 ERROR]: #!#! skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui) Khoryl v1.0.6 SkBee v2.9.0 (https://github.com/ShaneBeee/SkBee) Reqn v1.2.3 >
[03:00:23 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.>
[03:00:23 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.>
[03:00:23 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.>
[03:00:23 ERROR]: #!#! In that case, you will be given instruction on how should you report it.>
[03:00:23 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.>
[03:00:23 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.>
[03:00:23 ERROR]: #!#! >
[03:00:23 ERROR]: #!#! Stack trace:>
[03:00:23 ERROR]: #!#! java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1>
[03:00:23 ERROR]: #!#!     at Khoryl-1.0.6.jar//me.limeglass.khoryl.lang.SetEffect.init(SetEffect.java:33)>
[03:00:23 ERROR]: #!#!     at Skript-2.6.4 (10).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:255)>
[03:00:23 ERROR]: #!#!     at Skript-2.6.4 (10).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)>
[03:00:23 ERROR]: #!#!     at Skript-2.6.4 (10).jar//ch.njol.skript.lang.Effect.parse(Effect.java:76)>
[03:00:23 ERROR]: #!#!     at Skript-2.6.4 (10).jar//ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:280)>
[03:00:23 ERROR]: #!#!     at Skript-2.6.4 (10).jar//ch.njol.skript.command.Commands$3$1.call(Commands.java:220)>
[03:00:23 ERROR]: #!#!     at Skript-2.6.4 (10).jar//ch.njol.skript.command.Commands$3$1.call(Commands.java:217)>
[03:00:23 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftFuture.run(CraftFuture.java:88)>
[03:00:23 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)>
[03:00:23 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1483)>
[03:00:23 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)>
[03:00:23 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)>
[03:00:23 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)>
[03:00:23 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)>
[03:00:23 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)>
[03:00:23 ERROR]: #!#! >
[03:00:23 ERROR]: #!#! Version Information:>
[03:00:23 ERROR]: #!#!   Skript: 2.6.4 (latest)>
[03:00:23 ERROR]: #!#!     Flavor: skriptlang-github>
[03:00:23 ERROR]: #!#!   Bukkit: 1.19.4-R0.1-SNAPSHOT>
[03:00:23 ERROR]: #!#!   Minecraft: 1.19.4>
[03:00:23 ERROR]: #!#!   Java: 17.0.1 (OpenJDK 64-Bit Server VM 17.0.1+12-alpine-r0)>
[03:00:23 ERROR]: #!#!   OS: Linux amd64 5.10.0-23-amd64>
[03:00:23 ERROR]: #!#! >
[03:00:23 ERROR]: #!#! Server platform: Paper>
[03:00:23 ERROR]: #!#! >
[03:00:23 ERROR]: #!#! Current node: null>
[03:00:23 ERROR]: #!#! Current item: null>
[03:00:23 ERROR]: #!#! >
[03:00:23 ERROR]: #!#! Thread: Server thread>
[03:00:23 ERROR]: #!#! >
[03:00:23 ERROR]: #!#! Language: english>
[03:00:23 ERROR]: #!#! Link parse mode: DISABLED>
[03:00:23 ERROR]: #!#! >
[03:00:23 ERROR]: #!#! End of Error.>
[03:00:23 ERROR]: #!#! >
```

**Comment by TheLimeGlass** [comment]
Fixed in 1.1.0
